import type { JSX } from 'woby'

export interface DemoEntry {
    id: string
    name: string
    category: string
    component: () => Promise<{ default: () => JSX.Element }>
    thumbnail?: string
}

export interface CategoryEntry {
    id: string
    name: string
    demos: DemoEntry[]
}

export const categories: CategoryEntry[] = [
    {
        id: 'basics',
        name: 'Basics',
        demos: [
            { id: 'webgl_plane', name: 'Plane', category: 'basics', component: () => import('./Plane') },
            { id: 'webgl_boxes', name: '3 Boxes + Click', category: 'basics', component: () => import('./Box3') },
            { id: 'webgl_basics_orbits', name: 'Basics Orbits', category: 'basics', component: () => import('./WebGLBasicsOrbits') },
            { id: 'webgl_boxes_click', name: 'Boxes + Click', category: 'basics', component: () => import('./Box2Click') },
            { id: 'webgl_static_text', name: 'Box + Static Text', category: 'basics', component: () => import('./BoxStaticText') },
            { id: 'webgl_html_text', name: 'Box + HTML Text', category: 'basics', component: () => import('./BoxHtmlText') },
            { id: 'webgl_group', name: 'Group', category: 'basics', component: () => import('./group') },
            { id: 'webgl_object3d', name: 'Object3D Add', category: 'basics', component: () => import('./Object3dAdd') },
        ]
    },
    {
        id: 'lines',
        name: 'Lines',
        demos: [
            { id: 'webgl_simple_line', name: 'Simple Line', category: 'lines', component: () => import('./SimpleLine') },
            { id: 'webgl_fat_lines', name: 'Fat Lines', category: 'lines', component: () => import('./FatLines') },
            { id: 'webgl_line3', name: 'Line Segments', category: 'lines', component: () => import('./Line3') },
            { id: 'webgl_d_lines', name: 'D Lines', category: 'lines', component: () => import('./DLine') },
            { id: 'webgl_fat_lines_advanced', name: 'Fat Lines Advanced', category: 'lines', component: () => import('./WebGLFatLines') },
            { id: 'webgl_lines', name: 'Lines', category: 'lines', component: () => import('./WebGLLines') },
            { id: 'webgl_lines_dashed', name: 'Dashed Lines', category: 'lines', component: () => import('./WebGLLinesDashed') },
            { id: 'webgl_lines_fat', name: 'Fat Lines (Line2)', category: 'lines', component: () => import('./WebGLLinesFat') },
            { id: 'webgl_lines_fat_wireframe', name: 'Fat Wireframe', category: 'lines', component: () => import('./WebGLLinesLineMaterialWireframe') },
            { id: 'webgl_lines_fat_raycasting', name: 'Fat Lines Raycasting', category: 'lines', component: () => import('./WebGLLinesFatRaycasting') },
            { id: 'webgl_lines_linematerial', name: 'LineMaterial Helix', category: 'lines', component: () => import('./WebGLLinesLineMaterial') },
            { id: 'webgl_lines_colors', name: 'Lines Colors', category: 'lines', component: () => import('./WebGLLinesColors') },
            { id: 'webgl_lines_sphere', name: 'Lines Sphere', category: 'lines', component: () => import('./WebGLLinesSphere') },
            { id: 'webgl_buffergeometry_lines_indexed', name: 'BufferGeometry Lines Indexed', category: 'lines', component: () => import('./WebGLBufferGeometryLinesIndexed') },
        ]
    },
    {
        id: 'effects',
        name: 'Effects',
        demos: [
            { id: 'webgl_effects_anaglyph', name: 'Anaglyph', category: 'effects', component: () => import('./WebGLEffectsAnaglyph') },
            { id: 'webgl_effects_stereo', name: 'Stereo', category: 'effects', component: () => import('./WebGLEffectsStereo') },
            { id: 'webgl_effects_stereo2', name: 'Stereo 2', category: 'effects', component: () => import('./WebGLEffectsStereo2') },
            { id: 'webgl_effects_stereo3', name: 'Stereo 3', category: 'effects', component: () => import('./WebGLEffectsStereo3') },
            { id: 'webgl_effects_parallaxbarrier', name: 'Parallax Barrier', category: 'effects', component: () => import('./WebGLEffectsParallaxBarrier') },
            { id: 'webgl_effects_ascii', name: 'ASCII Effect', category: 'effects', component: () => import('./WebGLEffectsAscii') },
            { id: 'webgl_effects_outline', name: 'Effects Outline', category: 'effects', component: () => import('./WebGLEffectsOutline') },
            { id: 'webgl_effects_peppersghost', name: 'Peppers Ghost', category: 'effects', component: () => import('./WebGLEffectsPeppersGhost') },
        ]
    },
    {
        id: 'animation',
        name: 'Animation',
        demos: [
            { id: 'webgl_animation_keyframe', name: 'Animation Keyframe', category: 'animation', component: () => import('./AnimationKeyframe') },
            { id: 'webgl_animation_particles', name: 'Animation Particles', category: 'animation', component: () => import('./AnimationParticles') },
            { id: 'webgl_animation_keyframes', name: 'Animation Keyframes', category: 'animation', component: () => import('./AnimationKeyframes') },
            { id: 'webgl_animation_skinning', name: 'Animation Skinning', category: 'animation', component: () => import('./AnimationSkinning') },
            { id: 'webgl_morph_targets', name: 'Morph Targets', category: 'animation', component: () => import('./WebGLAnimationMorphTargets') },
            { id: 'webgl_animation_water_ripple', name: 'Water Ripple', category: 'animation', component: () => import('./WebGLAnimationWaterRipple') },
            { id: 'webgl_animation_skinning_blending', name: 'Skinning Blending', category: 'animation', component: () => import('./WebGLAnimationSkinningBlending') },
            { id: 'webgl_animation_skinning_additive_blending', name: 'Additive Blending', category: 'animation', component: () => import('./WebGLAnimationSkinningAdditiveBlending') },
            { id: 'webgl_animation_skinning_morph', name: 'Skinning Morph', category: 'animation', component: () => import('./WebGLAnimationSkinningMorph') },
            { id: 'webgl_animation_multiple', name: 'Multiple Animations', category: 'animation', component: () => import('./WebGLAnimationMultiple') },
            { id: 'webgl_animation_walk', name: 'Animation Walk', category: 'animation', component: () => import('./WebGLAnimationWalk') },
            { id: 'webgl_animation_morph', name: 'Animation Morph', category: 'animation', component: () => import('./WebGLAnimationMorph') },
            { id: 'webgl_animation_keyframes_sky', name: 'Animation Keyframes Sky', category: 'animation', component: () => import('./WebGLAnimationKeyframes') },
            { id: 'webgl_animation_locomotion', name: 'Animation Locomotion', category: 'animation', component: () => import('./WebGLAnimationLocomotion') },
            { id: 'webgl_animation_locomotive', name: 'Animation Locomotive', category: 'animation', component: () => import('./WebGLAnimationLocomotive') },
            { id: 'webgl_animation_ik', name: 'Animation IK', category: 'animation', component: () => import('./WebGLAnimationIK') },
            { id: 'webgl_animation_skinning_ik', name: 'Skinning IK', category: 'animation', component: () => import('./WebGLAnimationSkinningIK') },
            { id: 'misc_animation_groups', name: 'Animation Groups', category: 'animation', component: () => import('./MiscAnimationGroups') },
            { id: 'webgl_morphtargets_sphere', name: 'Morph Targets Sphere', category: 'animation', component: () => import('./WebGLMorphTargetsSphere') },
            { id: 'webgl_morphtargets_flamingo', name: 'Morph Targets Flamingo', category: 'animation', component: () => import('./WebGLMorphTargetsFlamingo') },
            { id: 'webgl_morphtargets_horse', name: 'Morph Targets Horse', category: 'animation', component: () => import('./WebGLMorphTargetsHorse') },
            { id: 'webgl_morphtargets_prog', name: 'Morph Targets Programmatic', category: 'animation', component: () => import('./WebGLMorphTargets') },
            { id: 'webgl_animation_walk_blend', name: 'Walk Cycle Blend', category: 'animation', component: () => import('./WebGLAnimationWalkBlend') },
            { id: 'webgl_animation_cloth', name: 'Cloth Simulation', category: 'animation', component: () => import('./WebGLAnimationCloth') },
            { id: 'webgl_animation_cloth2', name: 'Cloth Flag', category: 'animation', component: () => import('./WebGLAnimationCloth2') },
            { id: 'webgl_animation_cloth3', name: 'Cloth Flag Wind', category: 'animation', component: () => import('./WebGLAnimationCloth3') },
            { id: 'webgl_animation_robot', name: 'Robot Arm', category: 'animation', component: () => import('./WebGLAnimationRobot') },
            { id: 'webgl_animation_skeleton', name: 'Animation Skeleton', category: 'animation', component: () => import('./WebGLAnimationSkeleton') },
            { id: 'webgl_animation_skinning_basic', name: 'Skinning Basic', category: 'animation', component: () => import('./WebGLAnimationSkinningBasic') },
            { id: 'webgl_animation_crowd', name: 'Crowd Simulation', category: 'animation', component: () => import('./WebGLAnimationCrowd') },
            { id: 'webgl_animation_pendulum', name: 'Double Pendulum', category: 'animation', component: () => import('./WebGLAnimationPendulum') },
            { id: 'webgl_animation_flocking', name: 'Flocking (CPU Boids)', category: 'animation', component: () => import('./WebGLAnimationFlocking') },
            { id: 'webgl_animation_birds', name: 'Birds Flocking (Boids)', category: 'animation', component: () => import('./WebGLAnimationBirds') },
            { id: 'webgl_gpgpu_birds', name: 'GPGPU Birds (GPU Boids)', category: 'animation', component: () => import('./WebGLGPGPUBirds') },
            { id: 'webgl_animation_spring', name: 'Spring Physics Chain', category: 'animation', component: () => import('./WebGLAnimationSpring') },
            { id: 'webgl_animation_blend', name: 'Animation Blending', category: 'animation', component: () => import('./WebGLAnimationBlend') },
        ]
    },
    {
        id: 'geometries',
        name: 'Geometries',
        demos: [
            { id: 'webgl_geometries', name: 'All Geometries', category: 'geometries', component: () => import('./Geometries') },
            { id: 'webgl_text_geometry', name: 'Text Geometry', category: 'geometries', component: () => import('./TextGeometry') },
            { id: 'webgl_geometry_cube', name: 'Geometry Cube', category: 'geometries', component: () => import('./WebGLGeometryCube') },
            { id: 'webgl_geometries_showcase', name: 'All Geometries Showcase', category: 'geometries', component: () => import('./WebGLGeometries') },
            { id: 'webgl_geometries_tube', name: 'Tube Geometry', category: 'geometries', component: () => import('./WebGLGeometriesTube') },
            { id: 'webgl_geometry_shapes', name: 'Geometry Shapes', category: 'geometries', component: () => import('./WebGLGeometryShapes') },
            { id: 'webgl_geometry_cube2', name: 'Simple Cube', category: 'geometries', component: () => import('./WebGLGeometryCube2') },
            { id: 'webgl_geometry_lathe', name: 'Geometry Lathe', category: 'geometries', component: () => import('./WebGLGeometryLathe') },
            { id: 'webgl_geometries_lathe', name: 'Lathe Geometry', category: 'geometries', component: () => import('./WebGLGeometriesLathe') },
            { id: 'webgl_geometry_teapot', name: 'Utah Teapot', category: 'geometries', component: () => import('./WebGLGeometryTeapot') },
            { id: 'webgl_geometry_convex', name: 'Convex Geometry', category: 'geometries', component: () => import('./WebGLGeometryConvex') },
            { id: 'webgl_geometry_extrude_shapes', name: 'Extrude Shapes', category: 'geometries', component: () => import('./WebGLGeometryExtrudeShapes') },
            { id: 'webgl_geometry_extrusion', name: 'Shape Extrusion', category: 'geometries', component: () => import('./WebGLGeometryExtrusion') },
            { id: 'webgl_geometry_csg', name: 'CSG Geometry', category: 'geometries', component: () => import('./WebGLGeometryCSG') },
            { id: 'webgl_geometry_colors', name: 'Vertex Colors', category: 'geometries', component: () => import('./WebGLGeometryColors') },
            { id: 'webgl_geometry_colors_lut', name: 'Color Lookup Table', category: 'geometries', component: () => import('./WebGLGeometryColorsLookuptable') },
            { id: 'webgl_geometry_colors_lookuptable', name: 'LUT Colored Sphere (JSX)', category: 'geometries', component: () => import('./WebGLGeometryColorLookupTable') },
            { id: 'webgl_geometry_minecraft', name: 'Minecraft Terrain', category: 'geometries', component: () => import('./WebGLGeometryMinecraft') },
            { id: 'webgl_geometry_spline_editor', name: 'Spline Editor', category: 'geometries', component: () => import('./WebGLGeometrySplineEditor') },
            { id: 'webgl_geometry_spline_tube', name: 'Spline Tube Path', category: 'geometries', component: () => import('./WebGLGeometrySpline') },
            { id: 'webgl_geometry_text', name: '3D Text', category: 'geometries', component: () => import('./WebGLGeometryText') },
            { id: 'webgl_geometry_text_shapes', name: 'Text Shapes', category: 'geometries', component: () => import('./WebGLGeometryTextShapes') },
            { id: 'webgl_geometry_text_stroke', name: 'Text Stroke', category: 'geometries', component: () => import('./WebGLGeometryTextStroke') },
            { id: 'webgl_geometry_nurbs', name: 'NURBS', category: 'geometries', component: () => import('./WebGLGeometryNurbs') },
            { id: 'webgl_geometry_dynamic', name: 'Dynamic Geometry', category: 'geometries', component: () => import('./WebGLGeometryDynamic') },
            { id: 'webgl_geometry_parametric', name: 'Parametric Surfaces', category: 'geometries', component: () => import('./WebGLGeometryParametric') },
            { id: 'webgl_geometries_parametric', name: 'Parametric Geometries', category: 'geometries', component: () => import('./WebGLGeometriesParametric') },
            { id: 'webgl_geometry_extrude_splines', name: 'Extrude Splines', category: 'geometries', component: () => import('./WebGLGeometryExtrudeSplines') },
            { id: 'webgl_geometry_hierarchy', name: 'Geometry Hierarchy', category: 'geometries', component: () => import('./WebGLGeometryHierarchy') },
            { id: 'webgl_geometry_normals', name: 'Vertex Normals', category: 'geometries', component: () => import('./WebGLGeometryNormals') },
            { id: 'webgl_geometry_terrain', name: 'Procedural Terrain', category: 'geometries', component: () => import('./WebGLGeometryTerrain') },
            { id: 'webgl_geometry_procedural', name: 'Procedural Spiral', category: 'geometries', component: () => import('./WebGLGeometryProcedural') },
            { id: 'webgl_morphtargets', name: 'Morph Targets', category: 'geometries', component: () => import('./WebGLAnimationMorphTargets') },
            { id: 'webgl_geometry_gyroscope', name: 'Gyroscope', category: 'geometries', component: () => import('./WebGLGeometryGyroscope') },
            { id: 'webgl_geometry_morph', name: 'Morph Targets', category: 'geometries', component: () => import('./WebGLGeometryMorph') },
            { id: 'webgl_geometry_polyhedra', name: 'Platonic & Archimedean Solids', category: 'geometries', component: () => import('./WebGLGeometryPolyhedra') },
            { id: 'webgl_geometry_stellated', name: 'Stellated Icosahedron', category: 'geometries', component: () => import('./WebGLGeometryStellated') },
            { id: 'webgl_geometry_fractal', name: 'Fractal Geometry', category: 'geometries', component: () => import('./WebGLGeometryFractal') },
            { id: 'webgl_geometry_rolling', name: 'Rolling Shapes', category: 'geometries', component: () => import('./WebGLGeometryRolling') },
            { id: 'webgl_geometry_spiral', name: 'Spiral Galaxy', category: 'geometries', component: () => import('./WebGLGeometrySpiral') },
            { id: 'webgl_geometry_tube_fly', name: 'Tube Fly-Through', category: 'geometries', component: () => import('./WebGLGeometryTubeFly') },
            { id: 'webgl_geometry_warp', name: 'Mesh Warp Deformation', category: 'geometries', component: () => import('./WebGLGeometryWarp') },
            { id: 'webgl_geometry_convex_hull', name: 'Convex Hull Animated', category: 'geometries', component: () => import('./WebGLGeometryConvexHull') },
            { id: 'webgl_geometry_torusknot_shader', name: 'TorusKnot Shader', category: 'geometries', component: () => import('./WebGLGeometryTorusKnotShader') },
            { id: 'webgl_geometry_boolean', name: 'Boolean Operations', category: 'geometries', component: () => import('./WebGLGeometryBoolean') },
            { id: 'webgl_geometry_boolean_ops', name: 'Boolean Operations', category: 'geometries', component: () => import('./WebGLGeometryBooleanOps') },
            { id: 'webgl_geometry_lathe_profiles', name: 'Lathe Profiles', category: 'geometries', component: () => import('./WebGLGeometryLatheProfiles') },
            { id: 'webgl_geometry_subdivision', name: 'Mesh Subdivision', category: 'geometries', component: () => import('./WebGLGeometrySubdivision') },
            { id: 'webgl_geometry_noise_3d', name: '3D Noise Terrain', category: 'geometries', component: () => import('./WebGLGeometryNoise3D') },
            { id: 'webgl_geometry_extrude_text', name: 'Extruded Text', category: 'geometries', component: () => import('./WebGLGeometryExtrudeText') },
            { id: 'webgl_geometry_ocean_waves', name: 'Ocean Waves (Gerstner)', category: 'geometries', component: () => import('./WebGLGeometryOceanWaves') },
            { id: 'webgl_geometry_crystal', name: 'Crystal Cluster', category: 'geometries', component: () => import('./WebGLGeometryCrystal') },
            { id: 'webgl_geometry_instancing_perf', name: 'Instancing Performance (50k)', category: 'geometries', component: () => import('./WebGLGeometryInstancingPerf') },
            { id: 'webgl_geometry_metaballs', name: 'Metaballs (MarchingCubes)', category: 'geometries', component: () => import('./WebGLGeometryMetaballs') },
            { id: 'webgl_geometry_metaball', name: 'Metaballs', category: 'geometries', component: () => import('./WebGLGeometryMetaball') },
            { id: 'webgl_geometry_bubbles', name: 'Soap Bubbles', category: 'geometries', component: () => import('./WebGLGeometryBubbles') },
            { id: 'webgl_geometry_voronoi', name: 'Voronoi Pattern', category: 'geometries', component: () => import('./WebGLGeometryVoronoi') },
            { id: 'webgl_geometry_fractal_terrain', name: 'Fractal Terrain (Diamond-Square)', category: 'geometries', component: () => import('./WebGLGeometryFractalTerrain') },
            { id: 'webgl_geometry_fractal_landscape', name: 'Fractal Landscape', category: 'geometries', component: () => import('./WebGLGeometryFractalLandscape') },
            { id: 'webgl_geometry_mobius', name: 'Möbius Strip', category: 'geometries', component: () => import('./WebGLGeometryMobius') },
            { id: 'webgl_geometry_klein', name: 'Klein Bottle', category: 'geometries', component: () => import('./WebGLGeometryKlein') },
            { id: 'webgl_geometry_julia', name: 'Julia Set Fractal', category: 'geometries', component: () => import('./WebGLGeometryJulia') },
            { id: 'webgl_geometry_terrain_lod', name: 'Terrain LOD Chunks', category: 'geometries', component: () => import('./WebGLGeometryTerrainLOD') },
            { id: 'webgl_geometry_snowflake', name: 'Koch Snowflake', category: 'geometries', component: () => import('./WebGLGeometrySnowflake') },
            { id: 'webgl_geometry_reaction_diffusion', name: 'Reaction-Diffusion (Gray-Scott)', category: 'geometries', component: () => import('./WebGLGeometryReactionDiffusion') },
            { id: 'webgl_geometry_lissajous', name: 'Lissajous 3D Curves', category: 'geometries', component: () => import('./WebGLGeometryLissajous') },
            { id: 'webgl_geometry_wormhole', name: 'Wormhole Tunnel', category: 'geometries', component: () => import('./WebGLGeometryWormhole') },
            { id: 'webgl_geometry_mandelbrot', name: 'Mandelbrot Set', category: 'geometries', component: () => import('./WebGLGeometryMandelbrot') },
            { id: 'webgl_geometry_sphere_shader', name: 'Sphere Vertex Shader', category: 'geometries', component: () => import('./WebGLGeometrySphereShader') },
            { id: 'webgl_geometry_minecraft_ao', name: 'Minecraft AO', category: 'geometries', component: () => import('./WebGLGeometryMinecraftAO') },
            { id: 'webgl_geometry_planet', name: 'Planet (Earth + Atmosphere)', category: 'geometries', component: () => import('./WebGLGeometryPlanet') },
            { id: 'webgl_geometry_hyperboloid', name: 'Hyperboloid String Art', category: 'geometries', component: () => import('./WebGLGeometryHyperboloid') },
            { id: 'webgl_geometry_seashell', name: 'Seashell (Conchospiral)', category: 'geometries', component: () => import('./WebGLGeometrySeashell') },
            { id: 'webgl_geometry_lorenz', name: 'Lorenz Attractor', category: 'geometries', component: () => import('./WebGLGeometryLorenz') },
            { id: 'webgl_geometry_dna', name: 'DNA Double Helix', category: 'geometries', component: () => import('./WebGLGeometryDNA') },
            { id: 'webgl_geometry_torus_link', name: 'Linked Tori (Chain)', category: 'geometries', component: () => import('./WebGLGeometryTorusLink') },
            { id: 'webgl_geometry_fractal_tree', name: 'Fractal Tree (3D Branching)', category: 'geometries', component: () => import('./WebGLGeometryFractalTree') },
            { id: 'webgl_geometry_hypercube', name: 'Tesseract (4D Hypercube)', category: 'geometries', component: () => import('./WebGLGeometryHypercube') },
            { id: 'webgl_geometry_celtic_knot', name: 'Celtic Knot (Torus)', category: 'geometries', component: () => import('./WebGLGeometryCelticKnot') },
            { id: 'webgl_geometry_sphere_deform', name: 'Sphere Deformation', category: 'geometries', component: () => import('./WebGLGeometrySphereDeform') },
            { id: 'webgl_geometry_geodesic', name: 'Geodesic Dome', category: 'geometries', component: () => import('./WebGLGeometryGeodesic') },
            { id: 'webgl_geometry_crystal_lattice', name: 'Crystal Lattice (FCC)', category: 'geometries', component: () => import('./WebGLGeometryCrystalLattice') },
            { id: 'webgl_geometry_torusknot_unravel', name: 'Torus Knot Unravel', category: 'geometries', component: () => import('./WebGLGeometryTorusKnotUnravel') },
            { id: 'webgl_geometry_superquadric', name: 'Superquadric Shapes', category: 'geometries', component: () => import('./WebGLGeometrySuperquadric') },
            { id: 'webgl_geometry_boy_surface', name: "Boy's Surface", category: 'geometries', component: () => import('./WebGLGeometryBoySurface') },
            { id: 'webgl_geometry_bishop_curve', name: 'Bishop Curve', category: 'geometries', component: () => import('./WebGLGeometryBishopCurve') },
            { id: 'webgl_geometry_roman_surface', name: 'Roman Surface', category: 'geometries', component: () => import('./WebGLGeometryRomanSurface') },
            { id: 'webgl_geometry_enneper', name: 'Enneper Surface', category: 'geometries', component: () => import('./WebGLGeometryEnneper') },
            { id: 'webgl_geometry_dini', name: "Dini's Surface", category: 'geometries', component: () => import('./WebGLGeometryDini') },
            { id: 'webgl_geometry_crosscap', name: 'Cross-Cap Surface', category: 'geometries', component: () => import('./WebGLGeometryCrossCap') },
            { id: 'webgl_geometry_pseudosphere', name: 'Pseudosphere (Tractrix)', category: 'geometries', component: () => import('./WebGLGeometryPseudosphere') },
            { id: 'webgl_geometry_catalan', name: 'Catalan Surface', category: 'geometries', component: () => import('./WebGLGeometryCatalan') },
            { id: 'webgl_geometry_saddle', name: 'Saddle Surface', category: 'geometries', component: () => import('./WebGLGeometrySaddle') },
            { id: 'webgl_geometry_corkscrew', name: 'Corkscrew Surface', category: 'geometries', component: () => import('./WebGLGeometryCorkscrew') },
            { id: 'webgl_geometry_helicoid', name: 'Helicoid (Minimal Surface)', category: 'geometries', component: () => import('./WebGLGeometryHelicoid') },
            { id: 'webgl_geometry_catenoid', name: 'Catenoid (Minimal Surface)', category: 'geometries', component: () => import('./WebGLGeometryCatenoid') },
            { id: 'webgl_geometry_henneberg', name: 'Henneberg Surface', category: 'geometries', component: () => import('./WebGLGeometryHenneberg') },
            { id: 'webgl_geometry_scherk', name: 'Scherk Surface', category: 'geometries', component: () => import('./WebGLGeometryScherk') },
            { id: 'webgl_geometry_moebius_strip', name: 'Möbius Strip (Parametric)', category: 'geometries', component: () => import('./WebGLGeometryMoebiusStrip') },
            { id: 'webgl_geometry_cylinder', name: 'Generalized Cylinder', category: 'geometries', component: () => import('./WebGLGeometryCylinder') },
            { id: 'webgl_geometry_kuen', name: "Kuen's Surface", category: 'geometries', component: () => import('./WebGLGeometryKuen') },
            { id: 'webgl_geometry_klein_bottle', name: 'Klein Bottle (Figure-8)', category: 'geometries', component: () => import('./WebGLGeometryKleinBottle') },
            { id: 'webgl_geometry_whitney_umbrella', name: 'Whitney Umbrella', category: 'geometries', component: () => import('./WebGLGeometryWhitneyUmbrella') },
            { id: 'webgl_geometry_surface_of_revolution', name: 'Surface of Revolution', category: 'geometries', component: () => import('./WebGLGeometrySurfaceOfRevolution') },
            { id: 'webgl_geometry_cone', name: 'Generalized Cone', category: 'geometries', component: () => import('./WebGLGeometryCone') },
            { id: 'webgl_geometry_steiner', name: 'Steiner Surface', category: 'geometries', component: () => import('./WebGLGeometrySteiner') },
            { id: 'webgl_geometry_ruled_surface', name: 'Ruled Surface', category: 'geometries', component: () => import('./WebGLGeometryRuledSurface') },
            { id: 'webgl_geometry_offset_surface', name: 'Offset Surface', category: 'geometries', component: () => import('./WebGLGeometryOffsetSurface') },
            { id: 'webgl_geometry_twisted_box', name: 'Twisted Box', category: 'geometries', component: () => import('./WebGLGeometryTwistedBox') },
            { id: 'webgl_geometry_prism', name: 'Generalized Prism', category: 'geometries', component: () => import('./WebGLGeometryPrism') },
            { id: 'webgl_geometry_blend_surface', name: 'Blend Surface', category: 'geometries', component: () => import('./WebGLGeometryBlendSurface') },
            { id: 'webgl_geometry_developable_surface', name: 'Developable Surface', category: 'geometries', component: () => import('./WebGLGeometryDevelopableSurface') },
            { id: 'webgl_geometry_marching_cubes', name: 'Marching Cubes', category: 'geometries', component: () => import('./WebGLGeometryMarchingCubes') },
            { id: 'webgl_geometry_voxel', name: 'Voxel Geometry', category: 'geometries', component: () => import('./WebGLGeometryVoxel') },
            { id: 'webgl_geometry_lsystem', name: 'L-System Geometry', category: 'geometries', component: () => import('./WebGLGeometryLSystem') },
            { id: 'webgl_geometry_menger_sponge', name: 'Menger Sponge', category: 'geometries', component: () => import('./WebGLGeometryMengerSponge') },
            { id: 'webgl_geometry_knots', name: 'Mathematical Knots', category: 'geometries', component: () => import('./WebGLGeometryKnots') },
            { id: 'webgl_geometry_sierpinski', name: 'Sierpinski Fractals', category: 'geometries', component: () => import('./WebGLGeometrySierpinski') },
            { id: 'webgl_geometry_tessellation', name: 'Tessellation Patterns', category: 'geometries', component: () => import('./WebGLGeometryTessellation') },
            { id: 'webgl_geometry_gears', name: 'Gear Mechanism', category: 'geometries', component: () => import('./WebGLGeometryGears') },
            { id: 'webgl_geometry_julia_set', name: 'Julia Set 3D', category: 'geometries', component: () => import('./WebGLGeometryJuliaSet') },
            { id: 'webgl_geometry_spring', name: 'Spring/Helix Geometry', category: 'geometries', component: () => import('./WebGLGeometrySpring') },
            { id: 'webgl_geometry_space_filling', name: 'Space-Filling Curves', category: 'geometries', component: () => import('./WebGLGeometrySpaceFilling') },
            { id: 'webgl_geometry_aperiodic', name: 'Aperiodic Tiling (Penrose)', category: 'geometries', component: () => import('./WebGLGeometryAperiodic') },
            { id: 'webgl_geometry_mandelbulb', name: 'Mandelbulb Fractal', category: 'geometries', component: () => import('./WebGLGeometryMandelbulb') },
            { id: 'webgl_geometry_points', name: 'Point Cloud Geometry', category: 'geometries', component: () => import('./WebGLGeometryPoints') },
            { id: 'webgl_geometry_chain', name: 'Chain Links', category: 'geometries', component: () => import('./WebGLGeometryChain') },
            { id: 'webgl_geometry_wireframe', name: 'Wireframe Effects', category: 'geometries', component: () => import('./WebGLGeometryWireframe') },
            { id: 'webgl_geometry_modifiers', name: 'Geometry Modifiers', category: 'geometries', component: () => import('./WebGLGeometryModifiers') },
            { id: 'webgl_geometry_decal', name: 'Decal Geometry', category: 'geometries', component: () => import('./WebGLGeometryDecal') },
            { id: 'webgl_geometry_loft', name: 'Loft Geometry', category: 'geometries', component: () => import('./WebGLGeometryLoft') },
            { id: 'webgl_geometry_sweep', name: 'Sweep Geometry', category: 'geometries', component: () => import('./WebGLGeometrySweep') },
            { id: 'webgl_geometry_skinning', name: 'Geometry Skinning', category: 'geometries', component: () => import('./WebGLGeometrySkinning') },
            { id: 'webgl_vertices', name: 'Vertex Displacement Wave', category: 'geometries', component: () => import('./WebGLVertices') },
        ]
    },
    {
        id: 'materials',
        name: 'Materials',
        demos: [
            { id: 'webgl_materials', name: 'Physical Materials', category: 'materials', component: () => import('./Materials') },
            { id: 'webgl_materials_all', name: 'All Materials', category: 'materials', component: () => import('./WebGLMaterials') },
            { id: 'webgl_materials_physical', name: 'Physical Material', category: 'materials', component: () => import('./WebGLMaterialsPhysical') },
            { id: 'webgl_materials_normal', name: 'Normal Materials', category: 'materials', component: () => import('./WebGLMaterialsNormal') },
            { id: 'webgl_materials_colors', name: 'Material Colors', category: 'materials', component: () => import('./WebGLMaterialsColors') },
            { id: 'webgl_materials_transparency', name: 'Transparency & Alpha', category: 'materials', component: () => import('./WebGLMaterialsTransparency') },
            { id: 'webgl_normal_map', name: 'Normal Map', category: 'materials', component: () => import('./WebGLNormalMap') },
            { id: 'webgl_materials_blending', name: 'Blending', category: 'materials', component: () => import('./WebGLMaterialsBlending') },
            { id: 'webgl_materials_matcap', name: 'Matcap Material', category: 'materials', component: () => import('./WebGLMaterialsMatcap') },
            { id: 'webgl_materials_cubemap', name: 'Cubemap Reflection', category: 'materials', component: () => import('./WebGLMaterialsCubemap') },
            { id: 'webgl_materials_car', name: 'Car Materials', category: 'materials', component: () => import('./WebGLMaterialsCar') },
            { id: 'webgl_materials_normalmap', name: 'Normal Map', category: 'materials', component: () => import('./WebGLMaterialsNormalmap') },
            { id: 'webgl_materials_physical_clearcoat', name: 'Clearcoat', category: 'materials', component: () => import('./WebGLMaterialsPhysicalClearcoat') },
            { id: 'webgl_materials_physical_transmission', name: 'Transmission', category: 'materials', component: () => import('./WebGLMaterialsPhysicalTransmission') },
            { id: 'webgl_materials_channels', name: 'Channels', category: 'materials', component: () => import('./WebGLMaterialsChannels') },
            { id: 'webgl_materials_cubemap_dynamic', name: 'Dynamic Cubemap', category: 'materials', component: () => import('./WebGLMaterialsCubemapDynamic') },
            { id: 'webgl_materials_toon', name: 'Toon Material', category: 'materials', component: () => import('./WebGLMaterialsToon') },
            { id: 'webgl_materials_bumpmap', name: 'Bump Map', category: 'materials', component: () => import('./WebGLMaterialsBumpMap') },
            { id: 'webgl_materials_alphahash', name: 'Alpha Hash', category: 'materials', component: () => import('./WebGLMaterialsAlphahash') },
            { id: 'webgl_materials_blending_custom', name: 'Custom Blending', category: 'materials', component: () => import('./WebGLMaterialsBlendingCustom') },
            { id: 'webgl_materials_cubemap_refraction', name: 'Cubemap Refraction', category: 'materials', component: () => import('./WebGLMaterialsCubemapRefraction') },
            { id: 'webgl_materials_displacementmap', name: 'Displacement Map', category: 'materials', component: () => import('./WebGLMaterialsDisplacementMap') },
            { id: 'webgl_materials_envmaps', name: 'Environment Maps', category: 'materials', component: () => import('./WebGLMaterialsEnvmaps') },
            { id: 'webgl_materials_subsurface_scattering', name: 'Subsurface Scattering', category: 'materials', component: () => import('./WebGLMaterialsSubsurfaceScattering') },
            { id: 'webgl_materials_texture_grid', name: 'Texture Grid', category: 'materials', component: () => import('./WebGLMaterialsTextureGuid') },
            { id: 'webgl_materials_video', name: 'Video Material', category: 'materials', component: () => import('./WebGLMaterialsVideo') },
            { id: 'webgl_materials_lightmap', name: 'Light Map', category: 'materials', component: () => import('./WebGLMaterialsLightMap') },
            { id: 'webgl_materials_wireframe', name: 'Wireframe Materials', category: 'materials', component: () => import('./WebGLMaterialsWireframe') },
            { id: 'webgl_materials_grid', name: 'Materials Grid (metalness/roughness)', category: 'materials', component: () => import('./WebGLMaterialsGrid') },
            { id: 'webgl_materials_variants', name: 'Material Variants', category: 'materials', component: () => import('./WebGLMaterialsVariants') },
            { id: 'webgl_materials_reflection', name: 'Real-time Reflection', category: 'materials', component: () => import('./WebGLMaterialsReflection') },
            { id: 'webgl_materials_refraction', name: 'Refraction', category: 'materials', component: () => import('./WebGLMaterialsRefraction') },
            { id: 'webgl_materials_emissive', name: 'Emissive Materials', category: 'materials', component: () => import('./WebGLMaterialsEmissive') },
            { id: 'webgl_materials_subsurface', name: 'Subsurface Scattering', category: 'materials', component: () => import('./WebGLMaterialsSubsurface') },
            { id: 'webgl_materials_depth', name: 'Depth Material', category: 'materials', component: () => import('./WebGLMaterialsDepth') },
            { id: 'webgl_materials_envmaps_groundprojection', name: 'Env Map Ground Projection', category: 'materials', component: () => import('./WebGLMaterialsEnvmapsGroundProjection') },
            { id: 'webgl_materials_iridescence', name: 'Iridescence (Thin Film)', category: 'materials', component: () => import('./WebGLMaterialsIridescence') },
            { id: 'webgl_materials_glass', name: 'Glass Material', category: 'materials', component: () => import('./WebGLMaterialsGlass') },
            { id: 'webgl_materials_fur', name: 'Fur (Shell Technique)', category: 'materials', component: () => import('./WebGLMaterialsFur') },
            { id: 'webgl_materials_sheen', name: 'Sheen (Cloth)', category: 'materials', component: () => import('./WebGLMaterialsSheen') },
            { id: 'webgl_materials_anisotropy', name: 'Anisotropy (Brushed Metal)', category: 'materials', component: () => import('./WebGLMaterialsAnisotropy') },
            { id: 'webgl_materials_dispersion', name: 'Dispersion (Chromatic)', category: 'materials', component: () => import('./WebGLMaterialsDispersion') },
            { id: 'webgl_materials_velvet', name: 'Velvet (Sheen Material)', category: 'materials', component: () => import('./WebGLMaterialsVelvet') },
            { id: 'webgl_materials_hologram', name: 'Hologram Effect', category: 'materials', component: () => import('./WebGLMaterialsHologram') },
            { id: 'webgl_materials_xray', name: 'X-Ray Material', category: 'materials', component: () => import('./WebGLMaterialsXRay') },
            { id: 'webgl_materials_wax', name: 'Wax Candles (Transmission)', category: 'materials', component: () => import('./WebGLMaterialsWax') },
            { id: 'webgl_materials_oil_slick', name: 'Oil Slick (Thin Film)', category: 'materials', component: () => import('./WebGLMaterialsOilSlick') },
            { id: 'webgl_materials_procedural', name: 'Procedural Materials', category: 'materials', component: () => import('./WebGLMaterialsProcedural') },
            { id: 'webgl_materials_skin', name: 'Skin SSS Approximation', category: 'materials', component: () => import('./WebGLMaterialsSkin') },
            { id: 'webgl_materials_texture', name: 'Texture Mapping', category: 'materials', component: () => import('./WebGLMaterialsTexture') },
            { id: 'webgl_materials_texture_canvas', name: 'Canvas Clock Texture', category: 'materials', component: () => import('./WebGLTextureCanvas2') },
            { id: 'webgl_materials_blend', name: 'Material Blending', category: 'materials', component: () => import('./WebGLMaterialsBlend') },
            { id: 'webgl_materials_dissolve', name: 'Dissolve Effect', category: 'materials', component: () => import('./WebGLMaterialsDissolve') },
            { id: 'webgl_materials_gradient', name: 'Gradient Materials', category: 'materials', component: () => import('./WebGLMaterialsGradient') },
            { id: 'webgl_materials_parallax', name: 'Parallax Mapping', category: 'materials', component: () => import('./WebGLMaterialsParallax') },
            { id: 'webgl_materials_variations_basic', name: 'Material Variations Basic', category: 'materials', component: () => import('./WebGLMaterialsVariationsBasic') },
            { id: 'webgl_materials_variations_lambert', name: 'Material Variations Lambert', category: 'materials', component: () => import('./WebGLMaterialsVariationsLambert') },
            { id: 'webgl_materials_variations_phong', name: 'Material Variations Phong', category: 'materials', component: () => import('./WebGLMaterialsVariationsPhong') },
            { id: 'webgl_materials_variations_standard', name: 'Material Variations Standard', category: 'materials', component: () => import('./WebGLMaterialsVariationsStandard') },
            { id: 'webgl_materials_variations_physical', name: 'Material Variations Physical', category: 'materials', component: () => import('./WebGLMaterialsVariationsPhysical') },
            { id: 'webgl_materials_variations_toon', name: 'Material Variations Toon', category: 'materials', component: () => import('./WebGLMaterialsVariationsToon') },
            { id: 'webgl_materials_variations', name: 'Material Types Showcase', category: 'materials', component: () => import('./WebGLMaterialsVariations') },
            { id: 'webgl_refraction', name: 'Refraction CubeCamera', category: 'materials', component: () => import('./WebGLRefraction') },
        ]
    },
    {
        id: 'textures',
        name: 'Textures',
        demos: [
            { id: 'webgl_textures_cube', name: 'Textures Cube', category: 'textures', component: () => import('./WebGLTexturesCube') },
            { id: 'webgl_uvs', name: 'UVs', category: 'textures', component: () => import('./WebGLUVs') },
            { id: 'webgl_framebuffer_texture', name: 'Framebuffer Texture', category: 'textures', component: () => import('./WebGLFramebufferTexture') },
            { id: 'webgl_depth_texture', name: 'Depth Texture', category: 'textures', component: () => import('./WebGLDepthTexture') },
            { id: 'webgl_textures_colorbar', name: 'Color Bar', category: 'textures', component: () => import('./WebGLTexturesColorbar') },
            { id: 'webgl_textures_compression', name: 'Compression', category: 'textures', component: () => import('./WebGLTexturesCompression') },
            { id: 'webgl_textures_kinetic', name: 'Kinetic', category: 'textures', component: () => import('./WebGLTexturesKinetic') },
            { id: 'webgl_textures_pmrem_brandt', name: 'PMREM Brandt', category: 'textures', component: () => import('./WebGLTexturesPMREMbrandt') },
            { id: 'webgl_textures_sequence', name: 'Sequence', category: 'textures', component: () => import('./WebGLTexturesSequence') },
            { id: 'webgl_rtt', name: 'Render to Texture', category: 'textures', component: () => import('./WebGLRTT') },
            { id: 'webgl_render_target_cube', name: 'Cube Render Target', category: 'textures', component: () => import('./WebGLRenderTargetCube') },
            { id: 'webgl_textures_anisotropy', name: 'Anisotropic Filtering', category: 'textures', component: () => import('./WebGLTexturesAnisotropy') },
            { id: 'webgl_textures_dynamic', name: 'Dynamic Canvas Texture', category: 'textures', component: () => import('./WebGLTexturesDynamic') },
            { id: 'webgl_textures_3d', name: '3D Volume Texture', category: 'textures', component: () => import('./WebGLTextures3D') },
            { id: 'webgl_textures_pmrem', name: 'PMREM Environment', category: 'textures', component: () => import('./WebGLTexturesPMREM') },
            { id: 'webgl_textures_video', name: 'Video Texture (Canvas)', category: 'textures', component: () => import('./WebGLTexturesVideo') },
            { id: 'webgl_loader_texture_exr', name: 'EXR Texture', category: 'textures', component: () => import('./WebGLLoaderTextureEXR') },
            { id: 'webgl_loader_texture_hdr', name: 'HDR Texture', category: 'textures', component: () => import('./WebGLLoaderTextureHDR') },
            { id: 'webgl_loader_texture_dds', name: 'DDS Texture', category: 'textures', component: () => import('./WebGLLoaderTextureDDS') },
            { id: 'webgl_loader_texture_tga', name: 'TGA Texture', category: 'textures', component: () => import('./WebGLLoaderTextureTGA') },
            { id: 'webgl_loader_texture_ktx2', name: 'KTX2 Texture (Basis)', category: 'textures', component: () => import('./WebGLLoaderTextureKTX2') },
            { id: 'webgl_loader_texture_webp', name: 'WebP Texture', category: 'textures', component: () => import('./WebGLLoaderTextureWebP') },
            { id: 'webgl_texture_uv', name: 'UV Mapping', category: 'textures', component: () => import('./WebGLTextureUV') },
            { id: 'webgl_texture_offset', name: 'Texture Offset', category: 'textures', component: () => import('./WebGLTextureOffset') },
            { id: 'webgl_texture_projection', name: 'Texture Projection', category: 'textures', component: () => import('./WebGLTextureProjection') },
            { id: 'webgl_texture_packing', name: 'Texture Packing', category: 'textures', component: () => import('./WebGLTexturePacking') },
            { id: 'webgl_texture_mipmaps', name: 'Texture Mipmaps', category: 'textures', component: () => import('./WebGLTextureMipmaps') },
            { id: 'webgl_texture_canvas', name: 'Canvas Texture', category: 'textures', component: () => import('./WebGLTextureCanvas') },
            { id: 'webgl_texture_filters', name: 'Texture Filters', category: 'textures', component: () => import('./WebGLTextureFilters') },
            { id: 'webgl_texture_anisotropy', name: 'Anisotropy', category: 'textures', component: () => import('./WebGLTextureAnisotropy') },
            { id: 'webgl_texture_from_buffers', name: 'Texture from Buffers (DataTexture)', category: 'textures', component: () => import('./WebGLTextureFromBuffers') },
            { id: 'webgl_textures_primitives', name: 'Textures on Primitives', category: 'textures', component: () => import('./WebGLTexturesPrimitives') },
            { id: 'webgl_textures_envmap', name: 'Env Map (CubeCamera)', category: 'textures', component: () => import('./WebGLTexturesEnvmap') },
            { id: 'webgl_textures_rotate', name: 'Texture Rotation', category: 'textures', component: () => import('./WebGLTexturesRotate') },
            { id: 'webgl_textures_checker', name: 'Checker (Anisotropy)', category: 'textures', component: () => import('./WebGLTexturesChecker') },
            { id: 'webgl_textures_displacement', name: 'Displacement Map', category: 'textures', component: () => import('./WebGLTexturesDisplacement') },
            { id: 'webgl_textures_gradients', name: 'Gradient Textures', category: 'textures', component: () => import('./WebGLTexturesGradients') },
        ]
    },
    {
        id: 'alpha',
        name: 'Alpha',
        demos: [
            { id: 'webgl_alpha', name: 'Alpha', category: 'alpha', component: () => import('./WebGLAlpha') },
            { id: 'webgl_alpha_blend_modes', name: 'Alpha Blend Modes', category: 'alpha', component: () => import('./WebGLAlphaBlendModes') },
        ]
    },
    {
        id: 'clipping',
        name: 'Clipping',
        demos: [
            { id: 'webgl_clipping', name: 'Clipping', category: 'clipping', component: () => import('./WebGLClipping') },
            { id: 'webgl_clipping_advanced', name: 'Clipping Advanced', category: 'clipping', component: () => import('./WebGLClippingAdvanced') },
            { id: 'webgl_clipping_intersection', name: 'Clipping Intersection', category: 'clipping', component: () => import('./WebGLClippingIntersection') },
            { id: 'webgl_clipping_intersect', name: 'Clipping Plane Intersect', category: 'clipping', component: () => import('./WebGLClippingIntersect') },
            { id: 'webgl_clipping_stencil', name: 'Clipping Stencil', category: 'clipping', component: () => import('./WebGLClippingStencil') },
            { id: 'webgl_stencil_buffer', name: 'Stencil Buffer Portal', category: 'clipping', component: () => import('./WebGLStencilBuffer') },
        ]
    },
    {
        id: 'wireframes',
        name: 'Wireframes',
        demos: [
            { id: 'webgl_wireframes', name: 'Wireframes', category: 'wireframes', component: () => import('./WebGLWireframes') },
            { id: 'webgl_wireframes_solid', name: 'Wireframes Solid', category: 'wireframes', component: () => import('./WebGLWireframesSolid') },
            { id: 'webgl_wireframe', name: 'Wireframe Torus Knot', category: 'wireframes', component: () => import('./WebGLWireframe') },
        ]
    },
    {
        id: 'particles',
        name: 'Particles',
        demos: [
            { id: 'webgl_particles', name: 'Particles', category: 'particles', component: () => import('./WebGLParticles') },
            { id: 'webgl_particles_buffer', name: 'Particles Buffer', category: 'particles', component: () => import('./ParticlesBuffer') },
            { id: 'webgl_particles_basic', name: 'Particles Basic', category: 'particles', component: () => import('./Particles') },
            { id: 'webgl_points_sprites', name: 'Points Sprites', category: 'particles', component: () => import('./WebGLPointsSprites') },
            { id: 'webgl_points_dynamic', name: 'Points Dynamic', category: 'particles', component: () => import('./WebGLPointsDynamic') },
            { id: 'webgl_points_waves', name: 'Points Waves', category: 'particles', component: () => import('./WebGLPointsWaves') },
            { id: 'webgl_points_billboards', name: 'Points Billboards', category: 'particles', component: () => import('./WebGLPointsBillboards') },
            { id: 'webgl_particles_snow', name: 'Snow Particles', category: 'particles', component: () => import('./WebGLParticlesSnow') },
            { id: 'webgl_particles_galaxy', name: 'Galaxy', category: 'particles', component: () => import('./WebGLParticlesGalaxy') },
            { id: 'webgl_particles_wave', name: 'Particle Wave', category: 'particles', component: () => import('./WebGLParticlesWave') },
            { id: 'webgl_particles_firework', name: 'Firework', category: 'particles', component: () => import('./WebGLParticlesFirework') },
            { id: 'webgl_volume_cloud', name: 'Volume Cloud', category: 'particles', component: () => import('./WebGLVolumeCloud') },
            { id: 'webgl_custom_attributes_points', name: 'Custom Attributes Points', category: 'particles', component: () => import('./WebGLCustomAttributesPoints') },
            { id: 'webgl_particles_rain', name: 'Rain Particles', category: 'particles', component: () => import('./WebGLParticlesRain') },
            { id: 'webgl_particles_magnet', name: 'Magnetic Field Lines', category: 'particles', component: () => import('./WebGLParticlesMagnet') },
            { id: 'webgl_particles_smoke', name: 'Smoke Particles', category: 'particles', component: () => import('./WebGLParticlesSmoke') },
            { id: 'webgl_particles_constellation', name: 'Star Constellation', category: 'particles', component: () => import('./WebGLParticlesConstellation') },
            { id: 'webgl_particles_fire', name: 'Fire Particles', category: 'particles', component: () => import('./WebGLParticlesFire') },
            { id: 'webgl_particles_fireflies', name: 'Fireflies', category: 'particles', component: () => import('./WebGLParticlesFireflies') },
            { id: 'webgl_particles_sparks', name: 'Welding Sparks', category: 'particles', component: () => import('./WebGLParticlesSparks') },
            { id: 'webgl_particles_aurora', name: 'Aurora Borealis', category: 'particles', component: () => import('./WebGLParticlesAurora') },
            { id: 'webgl_particles_nebula', name: 'Space Nebula', category: 'particles', component: () => import('./WebGLParticlesNebula') },
            { id: 'webgl_particles_confetti', name: 'Confetti Physics', category: 'particles', component: () => import('./WebGLParticlesConfetti') },
            { id: 'webgl_particles_liquid', name: 'Liquid Simulation (SPH)', category: 'particles', component: () => import('./WebGLParticlesLiquid') },
            { id: 'webgl_particles_gravity_well', name: 'Gravity Well Attractors', category: 'particles', component: () => import('./WebGLParticlesGravityWell') },
            { id: 'webgl_particles_waves', name: 'Particle Wave Grid', category: 'particles', component: () => import('./WebGLParticlesWaves') },
            { id: 'webgl_particles_dynamic', name: 'Dynamic Particles (Bounce)', category: 'particles', component: () => import('./WebGLParticlesDynamic') },
        ]
    },
    {
        id: 'fog',
        name: 'Fog',
        demos: [
            { id: 'webgl_fog', name: 'Fog', category: 'fog', component: () => import('./WebGLFog') },
            { id: 'webgl_fog_exp2', name: 'Fog Exp2', category: 'fog', component: () => import('./WebGLFogExp2') },
        ]
    },
    {
        id: 'shadows',
        name: 'Shadows',
        demos: [
            { id: 'webgl_shadowmap', name: 'Shadow Map', category: 'shadows', component: () => import('./ShadowMap') },
            { id: 'webgl_shadowmap_advanced', name: 'Shadow Map Advanced', category: 'shadows', component: () => import('./WebGLShadowMap') },
            { id: 'webgl_shadow_contact', name: 'Shadow Contact', category: 'shadows', component: () => import('./WebGLShadowContact') },
            { id: 'webgl_shadows', name: 'Shadows', category: 'shadows', component: () => import('./WebGLShadows') },
            { id: 'webgl_shadowmap_pointlight', name: 'PointLight Shadows', category: 'shadows', component: () => import('./WebGLShadowmapPointlight') },
            { id: 'webgl_shadowmap_vsm', name: 'VSM Shadows', category: 'shadows', component: () => import('./WebGLShadowmapVSM') },
            { id: 'webgl_shadowmap_csm', name: 'Cascaded Shadow Maps', category: 'shadows', component: () => import('./WebGLShadowmapCSM') },
            { id: 'webgl_shadow_csm', name: 'Cascaded Shadow Maps', category: 'shadows', component: () => import('./WebGLShadowCSM') },
            { id: 'webgl_shadowmap_viewer', name: 'Shadow Map Viewer', category: 'shadows', component: () => import('./WebGLShadowmapViewer') },
            { id: 'webgl_shadowmap_performance', name: 'Shadowmap Performance', category: 'shadows', component: () => import('./WebGLShadowmapPerformance') },
            { id: 'webgl_shadowmesh', name: 'Shadow Mesh', category: 'shadows', component: () => import('./WebGLObjectsShadowMesh') },
            { id: 'webgl_shadows_bias', name: 'Shadow Bias', category: 'shadows', component: () => import('./WebGLShadowsBias') },
            { id: 'webgl_shadows_contact_soft', name: 'Soft Contact Shadows', category: 'shadows', component: () => import('./WebGLShadowsContactSoft') },
            { id: 'webgl_shadow_pcss', name: 'PCSS Soft Shadows', category: 'shadows', component: () => import('./WebGLShadowPCSS') },
            { id: 'webgl_shadowmap_pcss', name: 'Shadowmap PCSS', category: 'shadows', component: () => import('./WebGLShadowmapPCSS') },
            { id: 'webgl_shadowmap_progressive', name: 'Progressive Lightmap', category: 'shadows', component: () => import('./WebGLShadowmapProgressive') },
            { id: 'webgl_shadow_vsm', name: 'VSM Shadows', category: 'shadows', component: () => import('./WebGLShadowVSM') },
        ]
    },
    {
        id: 'lights',
        name: 'Lights',
        demos: [
            { id: 'webgl_lights', name: 'Physical Lights', category: 'lights', component: () => import('./WebGLLights') },
            { id: 'webgl_lights_rectarea', name: 'RectArea Lights', category: 'lights', component: () => import('./WebGLLightsRectArea') },
            { id: 'webgl_lights_spotlight', name: 'Spotlight', category: 'lights', component: () => import('./WebGLLightsSpotlight') },
            { id: 'webgl_lights_spotlights', name: 'Multiple Spotlights', category: 'lights', component: () => import('./WebGLLightsSpotlights') },
            { id: 'webgl_lightprobe', name: 'Light Probe', category: 'lights', component: () => import('./WebGLLightprobe') },
            { id: 'webgl_lights_hemisphere', name: 'Hemisphere Light', category: 'lights', component: () => import('./WebGLLightsHemisphere') },
            { id: 'webgl_lights_hemisphere2', name: 'Hemisphere Light (Full)', category: 'lights', component: () => import('./WebGLLightsHemisphere2') },
            { id: 'webgl_lights_hemispheric', name: 'Hemispheric Lighting', category: 'lights', component: () => import('./WebGLLightsHemispheric') },
            { id: 'webgl_lights_physical', name: 'Physical Lights', category: 'lights', component: () => import('./WebGLLightsPhysical') },
            { id: 'webgl_lights_pointlights', name: 'Point Lights', category: 'lights', component: () => import('./WebGLLightsPointLights') },
            { id: 'webgl_lights_rectarealight', name: 'Rect Area Light', category: 'lights', component: () => import('./WebGLLightsRectAreaLight') },
            { id: 'webgl_lights_spotlight_shadow', name: 'Spot Light Shadow', category: 'lights', component: () => import('./WebGLLightSpotShadow') },
            { id: 'webgl_lights_probe', name: 'Light Probe', category: 'lights', component: () => import('./WebGLLightsProbe') },
            { id: 'webgl_lights_area', name: 'Area Lights (RectArea)', category: 'lights', component: () => import('./WebGLLightsArea') },
            { id: 'webgl_lights_soft_shadow', name: 'Soft Shadows', category: 'lights', component: () => import('./WebGLLightsSoftShadow') },
            { id: 'webgl_light_area', name: 'Area Light', category: 'lights', component: () => import('./WebGLLightArea') },
            { id: 'webgl_light_volumetric', name: 'Volumetric Light', category: 'lights', component: () => import('./WebGLLightVolumetric') },
            { id: 'webgl_lightprobe_cubecamera', name: 'LightProbe CubeCamera', category: 'lights', component: () => import('./WebGLLightProbeCubeCamera') },
            { id: 'webgl_light_ies', name: 'IES Light Profile', category: 'lights', component: () => import('./WebGLLightIES') },
        ]
    },
    {
        id: 'cameras',
        name: 'Cameras',
        demos: [
            { id: 'webgl_camera', name: 'Camera', category: 'cameras', component: () => import('./WebGLCamera') },
            { id: 'webgl_camera_array', name: 'Camera Array', category: 'cameras', component: () => import('./WebGLCameraArray') },
            { id: 'webgl_camera_stereo', name: 'Stereo Camera', category: 'cameras', component: () => import('./WebGLCameraStereo') },
            { id: 'webgl_multiple_elements', name: 'Multiple Elements', category: 'cameras', component: () => import('./WebGLMultipleElements') },
            { id: 'webgl_camera_logarithmic_depth_buffer', name: 'Logarithmic Depth Buffer', category: 'cameras', component: () => import('./WebGLCameraLogarithmicDepthBuffer') },
            { id: 'webgl_panorama_cube', name: 'Panorama Cube', category: 'cameras', component: () => import('./WebGLPanoramaCube') },
            { id: 'webgl_camera_cinematic', name: 'Cinematic Camera Path', category: 'cameras', component: () => import('./WebGLCameraCinematic') },
            { id: 'webgl_multiple_cameras', name: 'Multiple Cameras (Split Screen)', category: 'cameras', component: () => import('./WebGLMultipleCameras') },
            { id: 'webgl_camera_path', name: 'Camera Path', category: 'cameras', component: () => import('./WebGLCameraPath') },
            { id: 'webgl_camera_zoom', name: 'Camera Zoom vs Dolly', category: 'cameras', component: () => import('./WebGLCameraZoom') },
            { id: 'webgl_multiple_views', name: 'Multiple Views (Split Screen)', category: 'cameras', component: () => import('./WebGLMultipleViews') },
            { id: 'webgl_multiple_elements_text', name: 'Multiple Elements + Text', category: 'cameras', component: () => import('./WebGLMultipleElementsText') },
        ]
    },
    {
        id: 'loaders',
        name: 'Loaders',
        demos: [
            { id: 'webgl_loader_gltf', name: 'GLTF Loader', category: 'loaders', component: () => import('./WebGLLoaderGLTF') },
            { id: 'webgl_loader_gltf_anisotropy', name: 'GLTF Anisotropy', category: 'loaders', component: () => import('./GltfAnisotropy') },
            { id: 'webgl_loader_gltf_demo', name: 'GLTF Demo', category: 'loaders', component: () => import('./WebGLLoaderGLTF') },
            { id: 'webgl_loader_gltf_2', name: 'GLTF 2', category: 'loaders', component: () => import('./WebGLLoaderGLTF2') },
            { id: 'webgl_loaders_gltf_animated', name: 'glTF Animated Character', category: 'loaders', component: () => import('./WebGLLoadersGltfAnimated') },
            { id: 'webgl_loader_obj', name: 'OBJ Loader', category: 'loaders', component: () => import('./WebGLLoaderOBJ') },
            { id: 'webgl_loader_draco', name: 'Draco Loader', category: 'loaders', component: () => import('./WebGLLoaderDraco') },
            { id: 'webgl_loader_fbx', name: 'FBX Loader', category: 'loaders', component: () => import('./WebGLLoaderFBX') },
            { id: 'webgl_loader_ply', name: 'PLY Loader', category: 'loaders', component: () => import('./WebGLLoaderPLY') },
            { id: 'webgl_loader_collada', name: 'Collada Loader', category: 'loaders', component: () => import('./WebGLLoaderCollada') },
            { id: 'webgl_loader_pcd', name: 'PCD Loader', category: 'loaders', component: () => import('./WebGLLoaderPCD') },
            { id: 'webgl_loader_vrml', name: 'VRML Loader', category: 'loaders', component: () => import('./WebGLLoaderVRML') },
            { id: 'webgl_loader_stl', name: 'STL Loader', category: 'loaders', component: () => import('./WebGLLoaderSTL') },
            { id: 'webgl_loader_3mf', name: '3MF Loader', category: 'loaders', component: () => import('./WebGLLoader3MF') },
            { id: 'webgl_loader_bvh', name: 'BVH Loader', category: 'loaders', component: () => import('./WebGLLoaderBVH') },
            { id: 'webgl_loader_gcode', name: 'GCode Loader', category: 'loaders', component: () => import('./WebGLLoaderGCode') },
            { id: 'webgl_loader_svg', name: 'SVG Loader', category: 'loaders', component: () => import('./WebGLLoaderSVG') },
            { id: 'webgl_loader_ttf', name: 'TTF Loader', category: 'loaders', component: () => import('./WebGLLoaderTTF') },
            { id: 'webgl_loader_pdb', name: 'PDB Loader', category: 'loaders', component: () => import('./WebGLLoaderPDB') },
            { id: 'webgl_loader_xyz', name: 'XYZ Loader', category: 'loaders', component: () => import('./WebGLLoaderXYZ') },
            { id: 'webgl_loader_3ds', name: '3DS Loader', category: 'loaders', component: () => import('./WebGLLoader3DS') },
            { id: 'webgl_loader_3dm', name: '3DM Loader', category: 'loaders', component: () => import('./WebGLLoader3DM') },
            { id: 'webgl_loader_amf', name: 'AMF Loader', category: 'loaders', component: () => import('./WebGLLoaderAMF') },
            { id: 'webgl_loader_kmz', name: 'KMZ Loader', category: 'loaders', component: () => import('./WebGLLoaderKMZ') },
            { id: 'webgl_loader_lwo', name: 'LWO Loader', category: 'loaders', component: () => import('./WebGLLoaderLWO') },
            { id: 'webgl_loader_md2', name: 'MD2 Loader', category: 'loaders', component: () => import('./WebGLLoaderMD2') },
            { id: 'webgl_loader_nrrd', name: 'NRRD Loader', category: 'loaders', component: () => import('./WebGLLoaderNRRD') },
            { id: 'webgl_loader_vox', name: 'VOX Loader', category: 'loaders', component: () => import('./WebGLLoaderVOX') },
            { id: 'webgl_loader_gltf_variants', name: 'GLTF Variants', category: 'loaders', component: () => import('./WebGLLoaderGLTFVariants') },
            { id: 'webgl_loader_gltf_compressed', name: 'GLTF Compressed', category: 'loaders', component: () => import('./WebGLLoaderGLTFCompressed') },
            { id: 'webgl_loader_gltf_lights', name: 'GLTF Lights (KHR_lights_punctual)', category: 'loaders', component: () => import('./WebGLLoaderGLTFLights') },
            { id: 'webgl_loader_gltf_browser', name: 'GLTF Model Browser', category: 'loaders', component: () => import('./GLTF') },
            { id: 'webgl_loader_texture_basis', name: 'Texture Basis (Compression)', category: 'loaders', component: () => import('./WebGLLoaderTextureBasis') },
        ]
    },
    {
        id: 'postprocessing',
        name: 'Postprocessing',
        demos: [
            { id: 'webgl_postprocessing', name: 'Unreal Bloom', category: 'postprocessing', component: () => import('./Postprocessing') },
            { id: 'webgl_postprocessing_demo', name: 'Postprocessing Demo', category: 'postprocessing', component: () => import('./WebGLPostprocessing') },
            { id: 'webgl_postprocessing_film', name: 'Film Effect', category: 'postprocessing', component: () => import('./PostprocessingFilm') },
            { id: 'webgl_postprocessing_ssao', name: 'SSAO', category: 'postprocessing', component: () => import('./WebGLPostprocessingSSAO') },
            { id: 'webgl_postprocessing_fxaa', name: 'FXAA', category: 'postprocessing', component: () => import('./WebGLPostprocessingFXAA') },
            { id: 'webgl_postprocessing_bokeh', name: 'Bokeh DOF', category: 'postprocessing', component: () => import('./WebGLPostprocessingBokeh') },
            { id: 'webgl_postprocessing_smaa', name: 'SMAA', category: 'postprocessing', component: () => import('./WebGLPostprocessingSMAA') },
            { id: 'webgl_postprocessing_vignette', name: 'Vignette', category: 'postprocessing', component: () => import('./WebGLPostprocessingVignette') },
            { id: 'webgl_color_grading', name: 'Color Grading', category: 'postprocessing', component: () => import('./WebGLColorGrading') },
            { id: 'webgl_postprocessing_dof', name: 'Depth of Field', category: 'postprocessing', component: () => import('./WebGLPostprocessingDOF') },
            { id: 'webgl_postprocessing_godrays', name: 'God Rays', category: 'postprocessing', component: () => import('./WebGLPostprocessingGodRays') },
            { id: 'webgl_postprocessing_outline', name: 'Outline', category: 'postprocessing', component: () => import('./WebGLPostprocessingOutline') },
            { id: 'webgl_postprocessing_ssr', name: 'Screen Space Reflections', category: 'postprocessing', component: () => import('./WebGLPostprocessingSSR') },
            { id: 'webgl_postprocessing_transition', name: 'Scene Transition', category: 'postprocessing', component: () => import('./WebGLPostprocessingTransition') },
            { id: 'webgl_postprocessing_glitch', name: 'Glitch', category: 'postprocessing', component: () => import('./WebGLPostprocessingGlitch') },
            { id: 'webgl_postprocessing_glow', name: 'Bloom Glow', category: 'postprocessing', component: () => import('./WebGLPostprocessingGlow') },
            { id: 'webgl_postprocessing_pixel', name: 'Pixel', category: 'postprocessing', component: () => import('./WebGLPostprocessingPixel') },
            { id: 'webgl_postprocessing_render_pixel', name: 'Pixelated Rendering', category: 'postprocessing', component: () => import('./WebGLPostprocessingRenderPixelated') },
            { id: 'webgl_postprocessing_afterimage', name: 'Afterimage', category: 'postprocessing', component: () => import('./WebGLPostprocessingAfterimage') },
            { id: 'webgl_postprocessing_taa', name: 'TAA', category: 'postprocessing', component: () => import('./WebGLPostprocessingTAA') },
            { id: 'webgl_postprocessing_temporal', name: 'Temporal AA', category: 'postprocessing', component: () => import('./WebGLPostprocessingTemporal') },
            { id: 'webgl_postprocessing_chromatic', name: 'Chromatic Aberration', category: 'postprocessing', component: () => import('./WebGLPostprocessingChromatic') },
            { id: 'webgl_postprocessing_depth', name: 'Depth Effect', category: 'postprocessing', component: () => import('./WebGLPostprocessingDepth') },
            { id: 'webgl_postprocessing_nodes', name: 'Node-based Effects', category: 'postprocessing', component: () => import('./WebGLPostprocessingNodes') },
            { id: 'webgl_postprocessing_advanced', name: 'Advanced', category: 'postprocessing', component: () => import('./WebGLPostprocessingAdvanced') },
            { id: 'webgl_postprocessing_bloom', name: 'Bloom', category: 'postprocessing', component: () => import('./WebGLPostprocessingBloom') },
            { id: 'webgl_postprocessing_bloom_hdr', name: 'Bloom HDR', category: 'postprocessing', component: () => import('./WebGLPostprocessingBloomHDR') },
            { id: 'webgl_postprocessing_lens_distortion', name: 'Lens Distortion', category: 'postprocessing', component: () => import('./WebGLPostprocessingLensDistortion') },
            { id: 'webgl_postprocessing_pixel_art', name: 'Pixel Art', category: 'postprocessing', component: () => import('./WebGLPostprocessingPixelArt') },
            { id: 'webgl_postprocessing_motionblur', name: 'Motion Blur', category: 'postprocessing', component: () => import('./WebGLPostprocessingMotionBlur') },
            { id: 'webgl_postprocessing_grayscale', name: 'Color Adjust (Grayscale/Sepia)', category: 'postprocessing', component: () => import('./WebGLPostprocessingGrayscale') },
            { id: 'webgl_postprocessing_colorgrading', name: 'Color Grading (Post)', category: 'postprocessing', component: () => import('./WebGLPostprocessingColorgrading') },
            { id: 'webgl_postprocessing_halftone', name: 'Halftone', category: 'postprocessing', component: () => import('./WebGLPostprocessingHalftone') },
            { id: 'webgl_postprocessing_dotscreen', name: 'Dot Screen', category: 'postprocessing', component: () => import('./WebGLPostprocessingDotScreen') },
            { id: 'webgl_postprocessing_mask', name: 'Masking', category: 'postprocessing', component: () => import('./WebGLPostprocessingMask') },
            { id: 'webgl_postprocessing_sao', name: 'SAO', category: 'postprocessing', component: () => import('./WebGLPostprocessingSAO') },
            { id: 'webgl_shader_kaleido', name: 'Kaleidoscope', category: 'postprocessing', component: () => import('./WebGLShaderKaleido') },
            { id: 'webgl_shader_sepia', name: 'Sepia / Vintage Film', category: 'postprocessing', component: () => import('./WebGLShaderSepia') },
            { id: 'webgl_postprocessing_crt', name: 'CRT Screen Effect', category: 'postprocessing', component: () => import('./WebGLPostprocessingCRT') },
            { id: 'webgl_postprocessing_ascii', name: 'ASCII Art Effect', category: 'postprocessing', component: () => import('./WebGLPostprocessingAscii') },
            { id: 'webgl_postprocessing_gtao', name: 'GTAO', category: 'postprocessing', component: () => import('./WebGLPostprocessingGTAO') },
            { id: 'webgl_postprocessing_3dlut', name: '3D LUT', category: 'postprocessing', component: () => import('./WebGLPostprocessing3DLUT') },
            { id: 'webgl_shader_tiltshift', name: 'Tilt Shift Blur', category: 'postprocessing', component: () => import('./WebGLShaderTiltShift') },
            { id: 'webgl_shader_sobel', name: 'Sobel Edge Detection', category: 'postprocessing', component: () => import('./WebGLShaderSobel') },
            { id: 'webgl_shader_rgbshift', name: 'RGB Shift', category: 'postprocessing', component: () => import('./WebGLShaderRGBShift') },
            { id: 'webgl_shader_hue_saturation', name: 'Hue/Saturation', category: 'postprocessing', component: () => import('./WebGLShaderHueSaturation') },
            { id: 'webgl_postprocessing_bloom_emissive', name: 'Bloom Emissive', category: 'postprocessing', component: () => import('./WebGLPostprocessingBloomEmissive') },
            { id: 'webgl_postprocessing_bloom_advanced', name: 'Bloom Advanced (Selective)', category: 'postprocessing', component: () => import('./WebGLPostprocessingBloomAdvanced') },
            { id: 'webgl_postprocessing_sobel', name: 'Sobel Edge Detection', category: 'postprocessing', component: () => import('./WebGLPostprocessingSobel') },
            { id: 'webgl_postprocessing_ssaa', name: 'SSAA Supersampling', category: 'postprocessing', component: () => import('./WebGLPostprocessingSSAA') },
            { id: 'webgl_postprocessing_masking', name: 'Masking / CopyShader', category: 'postprocessing', component: () => import('./WebGLPostprocessingMasking') },
            { id: 'webgl_postprocessing_unreal_bloom', name: 'Unreal Bloom (Emissive)', category: 'postprocessing', component: () => import('./WebGLPostprocessingUnrealBloom') },
            { id: 'webgl_postprocessing_dof2', name: 'Depth of Field (BokehPass)', category: 'postprocessing', component: () => import('./WebGLPostprocessingDOF2') },
            { id: 'webgl_postprocessing_screenspace', name: 'Screenspace Distortion', category: 'postprocessing', component: () => import('./WebGLPostprocessingScreenspace') },
        ]
    },
    {
        id: 'shaders',
        name: 'Shaders',
        demos: [
            { id: 'webgl_shader_fire', name: 'Fire Shader', category: 'shaders', component: () => import('./WebGLShaderFire') },
            { id: 'webgl_shader_demo', name: 'Custom Shaders', category: 'shaders', component: () => import('./WebGLShaderDemo') },
            { id: 'webgl_shaders_heatmap', name: 'Heatmap Shader', category: 'shaders', component: () => import('./WebGLShadersHeatmap') },
            { id: 'webgl_shader_distortion', name: 'Distortion Shaders', category: 'shaders', component: () => import('./WebGLShaderDistortion') },
            { id: 'webgl_shader_noise', name: 'Noise Shaders', category: 'shaders', component: () => import('./WebGLShaderNoise') },
            { id: 'webgl_shader_lavalamp', name: 'Shader Lava Lamp', category: 'shaders', component: () => import('./WebGLShaderLavaLamp') },
            { id: 'webgl_shader_vignette', name: 'Shader Vignette', category: 'shaders', component: () => import('./WebGLShaderVignette') },
            { id: 'webgl_shaders_sky', name: 'Shaders Sky', category: 'shaders', component: () => import('./WebGLShaderSky') },
            { id: 'webgl_shaders_ocean', name: 'Shaders Ocean', category: 'shaders', component: () => import('./WebGLShaderOcean') },
            { id: 'webgl_tonemapping', name: 'Tone Mapping', category: 'shaders', component: () => import('./WebGLShaderTonemapping') },
            { id: 'webgl_shaders_noise', name: 'Simplex Noise Shader', category: 'shaders', component: () => import('./WebGLShadersNoise') },
            { id: 'webgl_shaders', name: 'Glowing Circle Shader', category: 'shaders', component: () => import('./WebGLShaders') },
        ]
    },
    {
        id: 'environment',
        name: 'Environment',
        demos: [
            { id: 'webgl_sky', name: 'Sky', category: 'environment', component: () => import('./Sky') },
            { id: 'webgl_water', name: 'Water', category: 'environment', component: () => import('./Water') },
            { id: 'webgl_shaders_sky_environment', name: 'Sky Shader', category: 'environment', component: () => import('./WebGLShadersSky') },
            { id: 'webgl_shader_sky', name: 'Sky Shader 2', category: 'environment', component: () => import('./WebGLShaderSky') },
            { id: 'webgl_shader_ocean', name: 'Ocean Shader', category: 'environment', component: () => import('./WebGLShaderOcean') },
            { id: 'webgl_panorama_equirectangular', name: 'Equirectangular Panorama', category: 'environment', component: () => import('./WebGLPanoramaEquirectangular') },
            { id: 'webgl_environment_hdr', name: 'Environment HDR', category: 'environment', component: () => import('./WebGLEnvironmentHdr') },
        ]
    },
    {
        id: 'objects',
        name: 'Objects',
        demos: [
            { id: 'webgl_reflector', name: 'Reflector', category: 'objects', component: () => import('./Reflector') },
            { id: 'webgl_mirror', name: 'Mirror', category: 'objects', component: () => import('./WebGLMirror') },
            { id: 'webgl_objects_lod_cluster', name: 'LOD Cluster', category: 'objects', component: () => import('./WebGLObjectsLodCluster') },
            { id: 'webgl_lensflares', name: 'Lens Flares', category: 'objects', component: () => import('./WebGLLensflares') },
            { id: 'webgl_sector', name: 'Sector', category: 'objects', component: () => import('./Sector') },
            { id: 'webgl_marchingcubes', name: 'Marching Cubes', category: 'objects', component: () => import('./WebGLObjectsMarchingCubes') },
            { id: 'webgl_refractor', name: 'Refractor', category: 'objects', component: () => import('./WebGLObjectsRefractor') },
            { id: 'webgl_helpers_zoo', name: 'Helpers Zoo', category: 'objects', component: () => import('./WebGLMiscObjects') },
            { id: 'webgl_instanced_mesh_dynamic', name: 'Instanced Mesh Dynamic', category: 'objects', component: () => import('./WebGLInstancedMesh') },
        ]
    },
    {
        id: 'instancing',
        name: 'Instancing',
        demos: [
            { id: 'webgl_instancing', name: 'Instancing', category: 'instancing', component: () => import('./Instancing') },
            { id: 'webgl_instancing_performance', name: 'Instancing Performance', category: 'instancing', component: () => import('./WebGLInstancingPerformance') },
            { id: 'webgl_instancing_animated', name: 'Instancing Animated', category: 'instancing', component: () => import('./WebGLInstancingAnimated') },
            { id: 'webgl_instancing_billboards', name: 'Instancing Billboards', category: 'instancing', component: () => import('./WebGLInstancingBillboards') },
            { id: 'webgl_instancing_scatter', name: 'Instancing Scatter', category: 'instancing', component: () => import('./WebGLInstancingScatter') },
            { id: 'webgl_instancing_morph', name: 'Instancing Morph', category: 'instancing', component: () => import('./WebGLInstancingMorph') },
            { id: 'webgl_instancing_dynamic', name: 'Instancing Dynamic', category: 'instancing', component: () => import('./WebGLInstancingDynamic') },
            { id: 'webgl_instancing_grass', name: 'Instanced Grass', category: 'instancing', component: () => import('./WebGLInstancingGrass') },
            { id: 'webgl_instancing_raycast', name: 'Instancing Raycast', category: 'instancing', component: () => import('./WebGLInstancingRaycast') },
            { id: 'webgl_mesh_batch', name: 'Batched Mesh', category: 'instancing', component: () => import('./WebGLInstancingBatched') },
            { id: 'webgl_instancing_lod', name: 'Instancing LOD', category: 'instancing', component: () => import('./WebGLInstancingLOD') },
            { id: 'webgl_instancing_trees', name: 'Instanced Trees', category: 'instancing', component: () => import('./WebGLInstancingTrees') },
        ]
    },
    {
        id: 'interactive',
        name: 'Interactive',
        demos: [
            { id: 'webgl_interactive_cubes', name: 'Interactive Cubes', category: 'interactive', component: () => import('./WebGLInteractiveCubes') },
            { id: 'webgl_interactive_cubes_raycaster', name: 'Interactive Cubes Raycaster', category: 'interactive', component: () => import('./WebGLInteractiveCubesRaycast') },
            { id: 'webgl_interactive_voxelpainter', name: 'Voxel Painter', category: 'interactive', component: () => import('./WebGLInteractiveVoxelpainter') },
            { id: 'webgl_interactive_buffer_geometry', name: 'Interactive BufferGeometry', category: 'interactive', component: () => import('./WebGLInteractiveBufferGeometry') },
            { id: 'webgl_interactive_cubes_gpu', name: 'Interactive Cubes GPU', category: 'interactive', component: () => import('./WebGLInteractiveCubesGPU') },
            { id: 'webgl_interactive_cubes_ortho', name: 'Interactive Cubes Ortho', category: 'interactive', component: () => import('./WebGLInteractiveCubesOrtho') },
            { id: 'webgl_interactive_lines', name: 'Interactive Lines', category: 'interactive', component: () => import('./WebGLInteractiveLines') },
            { id: 'webgl_interactive_raycasting_points', name: 'Interactive Raycasting Points', category: 'interactive', component: () => import('./WebGLInteractiveRaycastingPoints') },
            { id: 'misc_boxselection', name: 'Box Selection', category: 'interactive', component: () => import('./MiscBoxselection') },
            { id: 'misc_raycaster_helper', name: 'Raycaster Helper', category: 'interactive', component: () => import('./MiscRaycasterHelper') },
            { id: 'webgl_interactive_points', name: 'Interactive Points', category: 'interactive', component: () => import('./WebGLInteractivePoints') },
            { id: 'webgl_interactive_voxels', name: 'Voxel Builder', category: 'interactive', component: () => import('./WebGLInteractiveVoxels') },
            { id: 'webgl_interactive_draggablecubes', name: 'Draggable Cubes', category: 'interactive', component: () => import('./WebGLInteractiveDrag') },
            { id: 'webgl_interactive_pick', name: 'Object Picking', category: 'interactive', component: () => import('./WebGLInteractivePick') },
            { id: 'webgl_raycaster', name: 'Raycaster Spheres', category: 'interactive', component: () => import('./WebGLRaycaster') },
            { id: 'webgl_raycast_sprite', name: 'Raycast Sprite', category: 'interactive', component: () => import('./WebGLRaycastSprite') },
        ]
    },
    {
        id: 'sprites',
        name: 'Sprites',
        demos: [
            { id: 'webgl_sprites', name: 'Sprites', category: 'sprites', component: () => import('./WebGLSprites') },
            { id: 'webgl_sprites_billboard', name: 'Billboard Sprites', category: 'sprites', component: () => import('./WebGLSpritesBillboard') },
            { id: 'webgl_sprites_scene', name: 'Sprites Scene', category: 'sprites', component: () => import('./WebGLSpritesNodes') },
            { id: 'webgl_sprites_all', name: 'Sprites Showcase', category: 'sprites', component: () => import('./WebGLSpritesAll') },
        ]
    },
    {
        id: 'buffergeometry',
        name: 'BufferGeometry',
        demos: [
            { id: 'webgl_buffergeometry', name: 'BufferGeometry', category: 'buffergeometry', component: () => import('./WebGLBufferGeometry') },
            { id: 'webgl_buffergeometry_indexed', name: 'Indexed BufferGeometry', category: 'buffergeometry', component: () => import('./WebGLBuffergeometryIndexed') },
            { id: 'webgl_buffergeometry_lines', name: 'BufferGeometry Lines', category: 'buffergeometry', component: () => import('./WebGLBufferGeometryLines') },
            { id: 'webgl_buffergeometry_instancing', name: 'BufferGeometry Instancing', category: 'buffergeometry', component: () => import('./WebGLBufferGeometryInstancing') },
            { id: 'webgl_buffergeometry_drawrange', name: 'BufferGeometry DrawRange', category: 'buffergeometry', component: () => import('./WebGLBufferGeometryDrawRange') },
            { id: 'webgl_buffergeometry_custom_attributes', name: 'Custom Attributes Particles', category: 'buffergeometry', component: () => import('./WebGLBufferGeometryCustomAttributes') },
            { id: 'webgl_buffergeometry_rawshader', name: 'Raw Shader Points', category: 'buffergeometry', component: () => import('./WebGLBufferGeometryRawShader') },
            { id: 'webgl_buffergeometry_selective_draw', name: 'Selective Drawing', category: 'buffergeometry', component: () => import('./WebGLBufferGeometrySelectiveDrawing') },
            { id: 'webgl_buffergeometry_instanced', name: 'Instanced BufferGeometry', category: 'buffergeometry', component: () => import('./WebGLBufferGeometryInstanced') },
        ]
    },
    {
        id: 'css3d',
        name: 'CSS3D',
        demos: [
            { id: 'css3d_periodictable', name: 'Periodic Table', category: 'css3d', component: () => import('./css3d_periodictable') },
            { id: 'webgl_css3d', name: 'WebGL + CSS3D', category: 'css3d', component: () => import('./webgl_css3d') },
            { id: 'webgl_css3d_carousel', name: 'CSS3D Carousel', category: 'css3d', component: () => import('./WebGLCss3dCarousel') },
            { id: 'webgl_css3d_demo', name: 'CSS3D Demo', category: 'css3d', component: () => import('./WebGLCSS3D') },
            { id: 'css3d_mixed', name: 'Mixed', category: 'css3d', component: () => import('./CSS3DMixed') },
            { id: 'css3d_molecules', name: 'Molecules', category: 'css3d', component: () => import('./CSS3DMolecules') },
            { id: 'css3d_orthographic', name: 'Orthographic', category: 'css3d', component: () => import('./CSS3DOrthographic') },
        ]
    },
    {
        id: 'reflection',
        name: 'Reflection',
        demos: [
            { id: 'webgl_reflection', name: 'Reflection', category: 'reflection', component: () => import('./WebGLReflection') },
            { id: 'webgl_reflection_chrome', name: 'Reflection Chrome', category: 'reflection', component: () => import('./WebGLReflectionChrome') },
        ]
    },
    {
        id: 'canvas_texture',
        name: 'Canvas Texture',
        demos: [
            { id: 'webgl_canvas_texture', name: 'Canvas Texture', category: 'canvas_texture', component: () => import('./WebGLCanvasTexture') },
            { id: 'webgl_canvas_texture_animated', name: 'Canvas Texture Animated', category: 'canvas_texture', component: () => import('./WebGLCanvasTextureAnimated') },
        ]
    },
    {
        id: 'toon',
        name: 'Toon',
        demos: [
            { id: 'webgl_toon', name: 'Toon Shading', category: 'toon', component: () => import('./WebGLToon') },
            { id: 'webgl_toon_inkline', name: 'Toon Inkline', category: 'toon', component: () => import('./WebGLToonInkline') },
        ]
    },
    {
        id: 'svg',
        name: 'SVG',
        demos: [
            { id: 'svg_lines', name: 'SVG Lines', category: 'svg', component: () => import('./SVGLines') },
            { id: 'webgl_svg', name: 'SVG Shapes', category: 'svg', component: () => import('./WebGLSVG') },
            { id: 'webgl_svg_extrude', name: 'SVG Extrude', category: 'svg', component: () => import('./WebGLSvgExtrude') },
        ]
    },
    {
        id: 'webgpu',
        name: 'WebGPU',
        demos: [
            { id: 'webgl_webgpu', name: 'WebGPU Style', category: 'webgpu', component: () => import('./WebGLWebGPU') },
            { id: 'webgl_webgpu_compute', name: 'WebGPU Compute (GPGPU sim)', category: 'webgpu', component: () => import('./WebGLWebgpuCompute') },
        ]
    },
    {
        id: 'point_cloud',
        name: 'Point Cloud',
        demos: [
            { id: 'webgl_point_cloud', name: 'Point Cloud', category: 'point_cloud', component: () => import('./WebGLPointCloud') },
            { id: 'webgl_point_cloud_animated', name: 'Point Cloud Animated', category: 'point_cloud', component: () => import('./WebGLPointCloudAnimated') },
            { id: 'webgl_pointcloud', name: 'Point Cloud (100k Random)', category: 'point_cloud', component: () => import('./WebGLPointCloud2') },
        ]
    },
    {
        id: 'terrain',
        name: 'Terrain',
        demos: [
            { id: 'webgl_terrain', name: 'Terrain', category: 'terrain', component: () => import('./WebGLTerrain') },
            { id: 'webgl_terrain_dynamic', name: 'Terrain Dynamic', category: 'terrain', component: () => import('./WebGLTerrainDynamic') },
        ]
    },
    {
        id: 'custom_shader',
        name: 'Custom Shader',
        demos: [
            { id: 'webgl_custom_shader', name: 'Custom Shader', category: 'custom_shader', component: () => import('./WebGLCustomShader') },
            { id: 'webgl_custom_shader_water', name: 'Custom Shader Water', category: 'custom_shader', component: () => import('./WebGLCustomShaderWater') },
            { id: 'webgl_shader_fresnel', name: 'Fresnel Shader', category: 'custom_shader', component: () => import('./WebGLShaderFresnel') },
            { id: 'webgl_shader_fresnel_cube', name: 'Fresnel Shader (Cube)', category: 'custom_shader', component: () => import('./WebGLShaderFresnelCube') },
            { id: 'webgl_shader_glow', name: 'Glow Effect', category: 'custom_shader', component: () => import('./WebGLShaderGlow') },
            { id: 'webgl_shader_hologram', name: 'Hologram Shader', category: 'custom_shader', component: () => import('./WebGLShaderHologram') },
            { id: 'webgl_shaders2', name: 'Shader: FBM Noise', category: 'custom_shader', component: () => import('./WebGLShaders2') },
            { id: 'webgl_shaders3', name: 'Shader: Ray March SDF', category: 'custom_shader', component: () => import('./WebGLShaders3') },
            { id: 'webgl_shaders4', name: 'Shader: Voronoi Noise', category: 'custom_shader', component: () => import('./WebGLShaders4') },
        ]
    },
    {
        id: 'physics',
        name: 'Physics',
        demos: [
            { id: 'webgl_physics', name: 'Physics', category: 'physics', component: () => import('./WebGLPhysics') },
            { id: 'webgl_physics_balls', name: 'Bouncing Balls Physics', category: 'physics', component: () => import('./WebGLPhysicsBalls') },
            { id: 'webgl_physics_cloth', name: 'Physics Cloth', category: 'physics', component: () => import('./WebGLPhysicsCloth') },
            { id: 'webgl_physics_rigid', name: 'Rigid Body Stacking', category: 'physics', component: () => import('./WebGLPhysicsRigid') },
            { id: 'physics_ammo_break', name: 'Ammo.js Breakable', category: 'physics', component: () => import('./PhysicsAmmoBreak') },
            { id: 'physics_ammo_cloth', name: 'Ammo.js Cloth', category: 'physics', component: () => import('./PhysicsAmmoCloth') },
            { id: 'physics_rapier_basic', name: 'Rapier Basic', category: 'physics', component: () => import('./PhysicsRapierBasic') },
            { id: 'physics_rapier_instancing', name: 'Rapier Instancing', category: 'physics', component: () => import('./PhysicsRapierInstancing') },
            { id: 'physics_rapier_joints', name: 'Rapier Joints', category: 'physics', component: () => import('./PhysicsRapierJoints') },
        ]
    },
    {
        id: 'audio',
        name: 'Audio',
        demos: [
            { id: 'webgl_audio', name: 'Audio Visualizer', category: 'audio', component: () => import('./WebGLAudio') },
            { id: 'webgl_audio_analyser', name: 'Audio Analyser', category: 'audio', component: () => import('./WebGLAudioAnalyser') },
            { id: 'webgl_audio_orientation', name: 'Audio Orientation', category: 'audio', component: () => import('./WebGLAudioOrientation') },
            { id: 'webgl_audio_positional', name: 'Positional Audio', category: 'audio', component: () => import('./WebGLAudioPositional') },
            { id: 'webgl_audio_visualizer', name: 'Audio Visualizer', category: 'audio', component: () => import('./WebGLAudioVisualizer') },
        ]
    },
    {
        id: 'css2d',
        name: 'CSS2D',
        demos: [
            { id: 'css2d_label', name: 'CSS2D Label', category: 'css2d', component: () => import('./CSS2DLabel') },
            { id: 'webgl_css2d', name: 'CSS2D Renderer', category: 'css2d', component: () => import('./WebGLCSS2D') },
            { id: 'webgl_css2d_chart', name: 'CSS2D Chart', category: 'css2d', component: () => import('./WebGLCss2dChart') },
        ]
    },
    {
        id: 'vr',
        name: 'VR',
        demos: [
            { id: 'webgl_vr', name: 'VR Experience', category: 'vr', component: () => import('./WebGLVR') },
        ]
    },
    {
        id: 'webxr',
        name: 'WebXR',
        demos: [
            { id: 'webgl_webxr', name: 'WebXR', category: 'webxr', component: () => import('./WebGLWebXR') },
            { id: 'webgl_webxr_ar', name: 'WebXR AR', category: 'webxr', component: () => import('./WebGLWebXRAR') },
            { id: 'webgl_webxr_vr', name: 'WebXR VR', category: 'webxr', component: () => import('./WebGLWebXRVR') },
            { id: 'webgl_webxr_hit_test', name: 'WebXR Hit Test', category: 'webxr', component: () => import('./WebGLWebXRHitTest') },
            { id: 'webgl_webxr_anchors', name: 'WebXR Anchors', category: 'webxr', component: () => import('./WebGLWebXRAnchors') },
            { id: 'webgl_webxr_layers', name: 'WebXR Layers', category: 'webxr', component: () => import('./WebGLWebXRLayers') },
            { id: 'webxr_ar_cones', name: 'WebXR AR Cones', category: 'webxr', component: () => import('./WebXRARCones') },
            { id: 'webxr_ar_plane_detection', name: 'WebXR AR Plane Detection', category: 'webxr', component: () => import('./WebXRARPlaneDetection') },
            { id: 'webxr_vr_ballshooter', name: 'WebXR VR Ball Shooter', category: 'webxr', component: () => import('./WebXRVRBallshooter') },
            { id: 'webxr_vr_paint', name: 'WebXR VR Paint', category: 'webxr', component: () => import('./WebXRVRPaint') },
            { id: 'webxr_sandbox', name: 'WebXR Sandbox', category: 'webxr', component: () => import('./WebXRSandbox') },
        ]
    },
    {
        id: 'advanced',
        name: 'Advanced',
        demos: [
            { id: 'webgl_batch_lod_bvh', name: 'Batch LOD BVH', category: 'advanced', component: () => import('./BatchLodBvh') },
            { id: 'webgl_useframe_test', name: 'UseFrame Test', category: 'advanced', component: () => import('./UseFrameTest') },
            { id: 'webgl_lod', name: 'Level of Detail', category: 'advanced', component: () => import('./WebGLLOD') },
            { id: 'webgl_decals', name: 'Decals', category: 'advanced', component: () => import('./WebGLDecals') },
            { id: 'webgl_modifier_simplify', name: 'Simplify Modifier', category: 'advanced', component: () => import('./WebGLModifierSimplify') },
            { id: 'webgl_modifier_curve', name: 'Curve Modifier', category: 'advanced', component: () => import('./WebGLModifierCurve') },
            { id: 'webgl_helpers', name: 'Helpers', category: 'advanced', component: () => import('./WebGLHelpers') },
            { id: 'webgl_multiple_geometries', name: 'Multiple Geometries', category: 'advanced', component: () => import('./WebGLMultipleGeometries') },
            { id: 'webgl_multiple_renderers', name: 'Multiple Renderers', category: 'advanced', component: () => import('./WebGLMultipleRenderers') },
            { id: 'webgl_tone_mapping', name: 'Tone Mapping', category: 'advanced', component: () => import('./WebGLToneMapping') },
            { id: 'webgl_shader_lava', name: 'Lava Shader', category: 'advanced', component: () => import('./WebGLShaderLava') },
            { id: 'webgl_shaders_ocean_advanced', name: 'Ocean Shader (Advanced)', category: 'advanced', component: () => import('./WebGLShadersOcean') },
            { id: 'webgl_modifier_tessellation', name: 'Tessellation Modifier', category: 'advanced', component: () => import('./WebGLModifierTessellation') },
            { id: 'webgl_modifier_edgesplit', name: 'Edge Split Modifier', category: 'advanced', component: () => import('./WebGLModifierEdgeSplit') },
            { id: 'webgl_performance', name: 'Performance (Instancing)', category: 'advanced', component: () => import('./WebGLPerformance') },
            { id: 'webgl_multiple_scenes', name: 'Multiple Scenes', category: 'advanced', component: () => import('./WebGLMultipleScenes') },
            { id: 'webgl_clipping_planes', name: 'Clipping Planes', category: 'advanced', component: () => import('./WebGLClippingPlanes') },
            { id: 'webgl_advanced_ssr', name: 'Screen Space Reflections', category: 'advanced', component: () => import('./WebGLAdvancedSSR') },
            { id: 'webgl_advanced_ssao', name: 'SSAO', category: 'advanced', component: () => import('./WebGLAdvancedSSAO') },
            { id: 'webgl_advanced_gtao', name: 'GTAO', category: 'advanced', component: () => import('./WebGLAdvancedGTAO') },
            { id: 'webgl_advanced_godrays', name: 'God Rays', category: 'advanced', component: () => import('./WebGLAdvancedGodRays') },
            { id: 'webgl_advanced_bloom', name: 'Bloom', category: 'advanced', component: () => import('./WebGLAdvancedBloom') },
            { id: 'webgl_advanced_pixelation', name: 'Pixelation', category: 'advanced', component: () => import('./WebGLAdvancedPixelation') },
            { id: 'webgl_advanced_vignette', name: 'Vignette', category: 'advanced', component: () => import('./WebGLAdvancedVignette') },
            { id: 'webgl_advanced_motionblur', name: 'Motion Blur', category: 'advanced', component: () => import('./WebGLAdvancedMotionBlur') },
            { id: 'webgl_advanced_dof', name: 'Depth of Field', category: 'advanced', component: () => import('./WebGLAdvancedDOF') },
            { id: 'webgl_advanced_chromatic', name: 'Chromatic Aberration', category: 'advanced', component: () => import('./WebGLAdvancedChromatic') },
            { id: 'webgl_advanced_outline', name: 'Outline Effect', category: 'advanced', component: () => import('./WebGLAdvancedOutline') },
            { id: 'webgl_advanced_fog', name: 'Volumetric Fog', category: 'advanced', component: () => import('./WebGLAdvancedFog') },
            { id: 'webgl_advanced_film', name: 'Film Grain', category: 'advanced', component: () => import('./WebGLAdvancedFilm') },
            { id: 'webgl_advanced_halftone', name: 'Halftone', category: 'advanced', component: () => import('./WebGLAdvancedHalftone') },
            { id: 'webgl_tonemapping_reinhard', name: 'Reinhard Tone Mapping', category: 'advanced', component: () => import('./WebGLTonemappingReinhard') },
            { id: 'webgl_performance_doublesided', name: 'Double-Sided Performance', category: 'advanced', component: () => import('./WebGLPerformanceDoublesided') },
            { id: 'webgl_performance_static', name: 'Static Instanced (10k)', category: 'advanced', component: () => import('./WebGLPerformanceStatic') },
            { id: 'webgl_marching_cubes', name: 'Marching Cubes', category: 'advanced', component: () => import('./WebGLMarchingCubes') },
            { id: 'webgl_multiple_rendertargets', name: 'Multiple Render Targets (MRT)', category: 'advanced', component: () => import('./WebGLMultipleRendertargets') },
        ]
    },
    {
        id: 'controls',
        name: 'Controls',
        demos: [
            { id: 'misc_controls_transform', name: 'Transform Controls', category: 'controls', component: () => import('./MiscControlsTransform') },
            { id: 'misc_controls_orbit', name: 'Orbit Controls', category: 'controls', component: () => import('./MiscControlsOrbit') },
            { id: 'misc_controls_trackball', name: 'Trackball Controls', category: 'controls', component: () => import('./MiscControlsTrackball') },
            { id: 'misc_controls_fly', name: 'Fly Controls', category: 'controls', component: () => import('./MiscControlsFly') },
            { id: 'misc_controls_drag', name: 'Drag Controls', category: 'controls', component: () => import('./MiscControlsDrag') },
            { id: 'misc_controls_arcball', name: 'Arcball Controls', category: 'controls', component: () => import('./MiscControlsArcball') },
            { id: 'misc_controls_firstperson', name: 'First Person Controls', category: 'controls', component: () => import('./MiscControlsFirstPerson') },
            { id: 'misc_controls_pointerlock', name: 'Pointer Lock Controls', category: 'controls', component: () => import('./MiscControlsPointerLock') },
            { id: 'misc_lookat', name: 'Look At Demo', category: 'controls', component: () => import('./WebGLMiscLookAt') },
            { id: 'webgl_controls_trackball', name: 'Trackball Controls', category: 'controls', component: () => import('./WebGLControlsTrackball') },
        ]
    },
]

// Flattened list for search
export const allDemos: DemoEntry[] = categories.flatMap(c => c.demos)
